### ISSUE TITLE
Error with DIA-NN conversion 

### ISSUE THREAD

**Issue by ypriverol** [bigbio/quantms#123]
### Description of feature

```
-[nf-core/quantms] Pipeline completed with errors-
Error executing process > 'NFCORE_QUANTMS:QUANTMS:DIA:DIANNCFG'

Caused by:
  Process `NFCORE_QUANTMS:QUANTMS:DIA:DIANNCFG` terminated with an error exit status (1)

Command executed:

  prepare_diann_parameters.py generate \
      --unimod_csv /hps/nobackup/juan/pride/reanalysis/quantms/assets/unimod.csv \
      --enzyme "Trypsin" \
      --fix_mod "" \
      --var_mod "Oxidation (M),Carbamidomethyl (C)" \
      --precursor_tolerence 10 \
      --precursor_tolerence_unit ppm \
      --fragment_tolerence 0.05 \
      --fragment_tolerence_unit Da \
      > GENERATE_DIANN_CFG.log
  
  cat <<-END_VERSIONS > versions.yml
  "NFCORE_QUANTMS:QUANTMS:DIA:DIANNCFG":
      python: "3.8.3"
  END_VERSIONS

Command exit status:
  1

Command output:
  (empty)

Command error:
  Traceback (most recent call last):
    File "/hps/nobackup/juan/pride/reanalysis/quantms/bin/prepare_diann_parameters.py", line 112, in <module>
      cli()
    File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1128, in __call__
      return self.main(*args, **kwargs)
    File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1053, in main
      rv = self.invoke(ctx)
    File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1659, in invoke
      return _process_result(sub_ctx.command.invoke(sub_ctx))
    File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1395, in invoke
      return ctx.invoke(self.callback, **ctx.params)
    File "/usr/local/lib/python3.10/site-packages/click/core.py", line 754, in invoke
      return __callback(*args, **kwargs)
    File "/usr/local/lib/python3.10/site-packages/click/decorators.py", line 26, in new_func
      return f(get_current_context(), *args, **kwargs)
    File "/hps/nobackup/juan/pride/reanalysis/quantms/bin/prepare_diann_parameters.py", line 24, in generate_cfg
      fix_ptm, var_ptm = convert_mod(unimod_csv, fix_mod, var_mod)
    File "/hps/nobackup/juan/pride/reanalysis/quantms/bin/prepare_diann_parameters.py", line 48, in convert_mod
      diann_mod = unimod[unimod['name'] == mod.split(" ")[0]]["params"].values[0]
  IndexError: index 0 is out of bounds for axis 0 with size 0

Work dir:
  /hps/nobackup/juan/pride/reanalysis/PXD004684/work/45/03eecf20422c9ec1dc64618878afa8

Tip: you can try to figure out what's wrong by changing to the process work dir and showing the script file named `.command.sh`

```

file here: https://raw.githubusercontent.com/multiomics/multiomics-configs/master/datasets/absolute-expression/tissues/PXD004684/PXD004684.sdrf.tsv

**Comment by daichengxin** [comment]
#124
