### ISSUE TITLE
pmultiqc error

### ISSUE THREAD

**Issue by ypriverol** [bigbio/quantms#258]
### Description of the bug

```
Error executing process > 'NFCORE_QUANTMS:QUANTMS:SUMMARYPIPELINE (1)'

Caused by:
  Process `NFCORE_QUANTMS:QUANTMS:SUMMARYPIPELINE (1)` terminated with an error exit status (1)

Command executed:

  multiqc \
      -f \
      --config ./results/multiqc_config.yml \
       \
       \
       \
      --quantification_method feature_intensity \
      ./results \
      -o .
  
  cat <<-END_VERSIONS > versions.yml
  "NFCORE_QUANTMS:QUANTMS:SUMMARYPIPELINE":
      pmultiqc: $(multiqc --pmultiqc_version | sed -e "s/pmultiqc, version //g")
  END_VERSIONS

Command exit status:
  1

Command output:
  (empty)

Command error:
  │     output = mod()                                                           │
  │   File "/usr/local/lib/python3.10/site-packages/pmultiqc/modules/quantms/qua │
  │     self.parse_diann_report()                                                │
  │   File "/usr/local/lib/python3.10/site-packages/pmultiqc/modules/quantms/qua │
  │     self.cal_num_table_data[i] = {'sample_name': self.exp_design_table[i]['S │
  │ KeyError: '20181012_QE8_nLC0_BDA_SA_DIA_P1_NN006_fibrobla.mzML'              │
  │                                                                              │
  ╰──────────────────────────────────────────────────────────────────────────────╯
  DEBUG:multiqc:Oops! The 'quantms' MultiQC module broke...
  ================================================================================
  Traceback (most recent call last):
    File "/usr/local/lib/python3.10/site-packages/multiqc/multiqc.py", line 654, in run
      output = mod()
    File "/usr/local/lib/python3.10/site-packages/pmultiqc/modules/quantms/quantms.py", line 164, in __init__
      self.parse_diann_report()
    File "/usr/local/lib/python3.10/site-packages/pmultiqc/modules/quantms/quantms.py", line 1705, in parse_diann_report
      self.cal_num_table_data[i] = {'sample_name': self.exp_design_table[i]['Sample'],
  KeyError: '20181012_QE8_nLC0_BDA_SA_DIA_P1_NN006_fibrobla.mzML'
  ================================================================================
  |    custom_content | nf-core-quantms-methods-description: Found 1 sample (html)
  INFO:multiqc.modules.custom_content.custom_content:nf-core-quantms-methods-description: Found 1 sample (html)
  |    custom_content | software_versions: Found 1 sample (html)
  INFO:multiqc.modules.custom_content.custom_content:software_versions: Found 1 sample (html)
  |    custom_content | nf-core-quantms-summary: Found 1 sample (html)
  INFO:multiqc.modules.custom_content.custom_content:nf-core-quantms-summary: Found 1 sample (html)
  DEBUG:multiqc:Reordering sections: anchor 'pmultiqc' not found.
  DEBUG:multiqc:Reordering sections: anchor 'pmultiqc' not found for module 'nf-core/quantms Methods Description'.
  DEBUG:multiqc:Reordering sections: anchor 'nf-core-quantms-methods-description' not found for module 'nf-core/quantms Methods Description'.
  DEBUG:multiqc:Reordering sections: anchor 'software_versions' not found for module 'nf-core/quantms Methods Description'.
  DEBUG:multiqc:Reordering sections: anchor 'nf-core-quantms-summary' not found for module 'nf-core/quantms Methods Description'.
  DEBUG:multiqc:Reordering sections: anchor 'pmultiqc' not found for module 'nf-core/quantms Software Versions'.
  DEBUG:multiqc:Reordering sections: anchor 'nf-core-quantms-methods-description' not found for module 'nf-core/quantms Software Versions'.
  DEBUG:multiqc:Reordering sections: anchor 'software_versions' not found for module 'nf-core/quantms Software Versions'.
  DEBUG:multiqc:Reordering sections: anchor 'nf-core-quantms-summary' not found for module 'nf-core/quantms Software Versions'.
  DEBUG:multiqc:Reordering sections: anchor 'pmultiqc' not found for module 'nf-core/quantms Workflow Summary'.
  DEBUG:multiqc:Reordering sections: anchor 'nf-core-quantms-methods-description' not found for module 'nf-core/quantms Workflow Summary'.
  DEBUG:multiqc:Reordering sections: anchor 'software_versions' not found for module 'nf-core/quantms Workflow Summary'.
  DEBUG:multiqc:Reordering sections: anchor 'nf-core-quantms-summary' not found for module 'nf-core/quantms Workflow Summary'.
  |           multiqc | Compressing plot data
  INFO:multiqc:Compressing plot data
  |           multiqc | Report      : multiqc_report.html
  INFO:multiqc:Report      : multiqc_report.html
  |           multiqc | Data        : multiqc_data
  INFO:multiqc:Data        : multiqc_data
  DEBUG:multiqc:Moving data file from '/hps/scratch/lsf_tmpdir/hl-codon-105-02/tmpls2sn7sm/multiqc_data' to './multiqc_data'
  |           multiqc | Plots       : multiqc_plots
  INFO:multiqc:Plots       : multiqc_plots
  DEBUG:multiqc:Moving plots directory from '/hps/scratch/lsf_tmpdir/hl-codon-105-02/tmpls2sn7sm/multiqc_plots' to './multiqc_plots'
  |           multiqc | MultiQC complete
  INFO:multiqc:MultiQC complete

Work dir:
  /hps/nobackup/juan/pride/reanalysis/absolute-expression/tissues/PXD019909/work/24/fd82e9f6dffeeab29402870389010d

Tip: view the complete command output by changing to the process work dir and entering the command `cat .command.out`

```

**Comment by ypriverol** [comment]
Another pmultiqc error: 

```

nf-core/quantms execution completed unsuccessfully!

The exit status of the task that caused the workflow execution to fail was: 1.

The full error message was:

Error executing process > 'NFCORE_QUANTMS:QUANTMS:SUMMARYPIPELINE (1)'

Caused by:
  Process `NFCORE_QUANTMS:QUANTMS:SUMMARYPIPELINE (1)` terminated with an error exit status (1)

Command executed:

  multiqc \
      -f \
      --config ./results/multiqc_config.yml \
       \
       \
       \
      --quantification_method feature_intensity \
      ./results \
      -o .
  
  cat <<-END_VERSIONS > versions.yml
  "NFCORE_QUANTMS:QUANTMS:SUMMARYPIPELINE":
      pmultiqc: $(multiqc --pmultiqc_version | sed -e "s/pmultiqc, version //g")
  END_VERSIONS

Command exit status:
  1

Command output:
  (empty)

Command error:
  │     output = mod()                                                           │
  │   File "/usr/local/lib/python3.10/site-packages/pmultiqc/modules/quantms/qua │
  │     self.parse_out_mzTab()                                                   │
  │   File "/usr/local/lib/python3.10/site-packages/pmultiqc/modules/quantms/qua │
  │     self.cal_num_table_data[i] = {'sample_name': self.exp_design_table[i]['S │
  │ KeyError: 'OS02252_01_LyscTryp.mzML'                                         │
  │                                                                              │
  ╰──────────────────────────────────────────────────────────────────────────────╯
  DEBUG:multiqc:Oops! The 'quantms' MultiQC module broke...
  ================================================================================
  Traceback (most recent call last):
    File "/usr/local/lib/python3.10/site-packages/multiqc/multiqc.py", line 654, in run
      output = mod()
    File "/usr/local/lib/python3.10/site-packages/pmultiqc/modules/quantms/quantms.py", line 152, in __init__
      self.parse_out_mzTab()
    File "/usr/local/lib/python3.10/site-packages/pmultiqc/modules/quantms/quantms.py", line 1407, in parse_out_mzTab
      self.cal_num_table_data[i] = {'sample_name': self.exp_design_table[i]['Sample'],
  KeyError: 'OS02252_01_LyscTryp.mzML'
  ================================================================================
  |    custom_content | nf-core-quantms-methods-description: Found 1 sample (html)
  INFO:multiqc.modules.custom_content.custom_content:nf-core-quantms-methods-description: Found 1 sample (html)
  |    custom_content | software_versions: Found 1 sample (html)
  INFO:multiqc.modules.custom_content.custom_content:software_versions: Found 1 sample (html)
  |    custom_content | nf-core-quantms-summary: Found 1 sample (html)
  INFO:multiqc.modules.custom_content.custom_content:nf-core-quantms-summary: Found 1 sample (html)
  DEBUG:multiqc:Reordering sections: anchor 'pmultiqc' not found.
  DEBUG:multiqc:Reordering sections: anchor 'pmultiqc' not found for module 'nf-core/quantms Methods Description'.
  DEBUG:multiqc:Reordering sections: anchor 'nf-core-quantms-methods-description' not found for module 'nf-core/quantms Methods Description'.
  DEBUG:multiqc:Reordering sections: anchor 'software_versions' not found for module 'nf-core/quantms Methods Description'.
  DEBUG:multiqc:Reordering sections: anchor 'nf-core-quantms-summary' not found for module 'nf-core/quantms Methods Description'.
  DEBUG:multiqc:Reordering sections: anchor 'pmultiqc' not found for module 'nf-core/quantms Software Versions'.
  DEBUG:multiqc:Reordering sections: anchor 'nf-core-quantms-methods-description' not found for module 'nf-core/quantms Software Versions'.
  DEBUG:multiqc:Reordering sections: anchor 'software_versions' not found for module 'nf-core/quantms Software Versions'.
  DEBUG:multiqc:Reordering sections: anchor 'nf-core-quantms-summary' not found for module 'nf-core/quantms Software Versions'.
  DEBUG:multiqc:Reordering sections: anchor 'pmultiqc' not found for module 'nf-core/quantms Workflow Summary'.
  DEBUG:multiqc:Reordering sections: anchor 'nf-core-quantms-methods-description' not found for module 'nf-core/quantms Workflow Summary'.
  DEBUG:multiqc:Reordering sections: anchor 'software_versions' not found for module 'nf-core/quantms Workflow Summary'.
  DEBUG:multiqc:Reordering sections: anchor 'nf-core-quantms-summary' not found for module 'nf-core/quantms Workflow Summary'.
  |           multiqc | Compressing plot data
  INFO:multiqc:Compressing plot data
  |           multiqc | Report      : multiqc_report.html
  INFO:multiqc:Report      : multiqc_report.html
  |           multiqc | Data        : multiqc_data
  INFO:multiqc:Data        : multiqc_data
  DEBUG:multiqc:Moving data file from '/hps/scratch/lsf_tmpdir/hl-codon-20-04/tmpukdk271a/multiqc_data' to './multiqc_data'
  |           multiqc | Plots       : multiqc_plots
  INFO:multiqc:Plots       : multiqc_plots
  DEBUG:multiqc:Moving plots directory from '/hps/scratch/lsf_tmpdir/hl-codon-20-04/tmpukdk271a/multiqc_plots' to './multiqc_plots'
  |           multiqc | MultiQC complete
  INFO:multiqc:MultiQC complete

Work dir:
  /hps/nobackup/juan/pride/reanalysis/absolute-expression/tissues/PXD004143/work/80/a86b18bc7e4d043380ca45f74ab92c

Tip: view the complete command output by changing to the process work dir and entering the command `cat .command.out`

```
