### ISSUE TITLE
Bug with mzTab export in single cell dataset

### ISSUE THREAD

**Issue by ypriverol** [bigbio/quantms#318]
### Description of the bug

```
Caused by:
  Process `NFCORE_QUANTMS:QUANTMS:DIA:DIANNCONVERT (PXD024043-diaPASEF-1ng.sdrf)` terminated with an error exit status (1)

Command executed:

  diann_convert.py convert \
      --folder ./ \
      --exp_design PXD024043-diaPASEF-1ng.sdrf_openms_design.tsv \
      --diann_version ./version/versions.yml \
      --dia_params "10.0;ppm;10.0;ppm;Trypsin;;Acetyl (Any N-term),Oxidation (M)" \
      --charge 4 \
      --missed_cleavages 1 \
      --qvalue_threshold 0.01 \
      2>&1 | tee convert_report.log
  
  cat <<-END_VERSIONS > versions.yml
  "NFCORE_QUANTMS:QUANTMS:DIA:DIANNCONVERT":
      pyopenms: $(pip show pyopenms | grep "Version" | awk -F ': ' '{print $2}')
  END_VERSIONS

Command exit status:
  1

Command output:
    out_mztab_MTD.loc[1, "software[1]-setting[6]"] = "precursor_mass_tolerance_unit:" + PrecursorMassToleranceUnit
  /hps/nobackup/juan/pride/reanalysis/quantms-ypriverol/quantms/bin/diann_convert.py:469: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value 'enzyme:Trypsin' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
    out_mztab_MTD.loc[1, "software[1]-setting[7]"] = "enzyme:" + Enzyme
  /hps/nobackup/juan/pride/reanalysis/quantms-ypriverol/quantms/bin/diann_convert.py:470: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value 'enzyme_term_specificity:full' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
    out_mztab_MTD.loc[1, "software[1]-setting[8]"] = "enzyme_term_specificity:full"
  /hps/nobackup/juan/pride/reanalysis/quantms-ypriverol/quantms/bin/diann_convert.py:471: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value 'charges:4' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
    out_mztab_MTD.loc[1, "software[1]-setting[9]"] = "charges:" + str(charge)
  /hps/nobackup/juan/pride/reanalysis/quantms-ypriverol/quantms/bin/diann_convert.py:472: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value 'missed_cleavages:1' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
    out_mztab_MTD.loc[1, "software[1]-setting[10]"] = "missed_cleavages:" + str(missed_cleavages)
  /hps/nobackup/juan/pride/reanalysis/quantms-ypriverol/quantms/bin/diann_convert.py:473: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value 'fixed_modifications:null' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
    out_mztab_MTD.loc[1, "software[1]-setting[11]"] = "fixed_modifications:" + FixedModifications
  /hps/nobackup/juan/pride/reanalysis/quantms-ypriverol/quantms/bin/diann_convert.py:474: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value 'variable_modifications:Acetyl (Any N-term),Oxidation (M)' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
    out_mztab_MTD.loc[1, "software[1]-setting[12]"] = "variable_modifications:" + VariableModifications
  const OpenMS::ResidueModification* OpenMS::ModificationsDB::searchModificationsFast(const OpenMS::String&, bool&, const OpenMS::String&, OpenMS::ResidueModification::TermSpecificity) constModification not found: Acetyl (Any N-term)
  Warning: OPENMS_DATA_PATH environment variable not found and no share directory was installed. Some functionality might not work as expected.
  Traceback (most recent call last):
    File "/hps/nobackup/juan/pride/reanalysis/quantms-ypriverol/quantms/bin/diann_convert.py", line 1333, in <module>
      cli()
    File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1157, in __call__
      return self.main(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1078, in main
      rv = self.invoke(ctx)
           ^^^^^^^^^^^^^^^^
    File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1688, in invoke
      return _process_result(sub_ctx.command.invoke(sub_ctx))
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1434, in invoke
      return ctx.invoke(self.callback, **ctx.params)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/usr/local/lib/python3.11/site-packages/click/core.py", line 783, in invoke
      return __callback(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/usr/local/lib/python3.11/site-packages/click/decorators.py", line 33, in new_func
      return f(get_current_context(), *args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/hps/nobackup/juan/pride/reanalysis/quantms-ypriverol/quantms/bin/diann_convert.py", line 144, in convert
      diann_directory.convert_to_mztab(
    File "/hps/nobackup/juan/pride/reanalysis/quantms-ypriverol/quantms/bin/diann_convert.py", line 304, in convert_to_mztab
      (MTD, database) = mztab_MTD(index_ref, dia_params, str(self.fasta), charge, missed_cleavages)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/hps/nobackup/juan/pride/reanalysis/quantms-ypriverol/quantms/bin/diann_convert.py", line 476, in mztab_MTD
      (fixed_mods, variable_mods, fix_flag, var_flag) = MTD_mod_info(FixedModifications, VariableModifications)
                                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/hps/nobackup/juan/pride/reanalysis/quantms-ypriverol/quantms/bin/diann_convert.py", line 412, in MTD_mod_info
      mod_obj = mods_db.getModification(mod)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "pyopenms/_pyopenms_1.pyx", line 8193, in pyopenms._pyopenms_1.ModificationsDB.getModification
    File "pyopenms/_pyopenms_1.pyx", line 8140, in pyopenms._pyopenms_1.ModificationsDB._getModification_1
  RuntimeError: the value 'Acetyl (Any N-term)' was used but is not valid; Retrieving the modification failed. It is not available for the residue '' and term specificity 'none'. 

Command wrapper:
    out_mztab_MTD.loc[1, "software[1]-setting[6]"] = "precursor_mass_tolerance_unit:" + PrecursorMassToleranceUnit
  /hps/nobackup/juan/pride/reanalysis/quantms-ypriverol/quantms/bin/diann_convert.py:469: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value 'enzyme:Trypsin' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
    out_mztab_MTD.loc[1, "software[1]-setting[7]"] = "enzyme:" + Enzyme
  /hps/nobackup/juan/pride/reanalysis/quantms-ypriverol/quantms/bin/diann_convert.py:470: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value 'enzyme_term_specificity:full' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
    out_mztab_MTD.loc[1, "software[1]-setting[8]"] = "enzyme_term_specificity:full"
  /hps/nobackup/juan/pride/reanalysis/quantms-ypriverol/quantms/bin/diann_convert.py:471: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value 'charges:4' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
    out_mztab_MTD.loc[1, "software[1]-setting[9]"] = "charges:" + str(charge)
  /hps/nobackup/juan/pride/reanalysis/quantms-ypriverol/quantms/bin/diann_convert.py:472: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value 'missed_cleavages:1' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
    out_mztab_MTD.loc[1, "software[1]-setting[10]"] = "missed_cleavages:" + str(missed_cleavages)
  /hps/nobackup/juan/pride/reanalysis/quantms-ypriverol/quantms/bin/diann_convert.py:473: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value 'fixed_modifications:null' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
    out_mztab_MTD.loc[1, "software[1]-setting[11]"] = "fixed_modifications:" + FixedModifications
  /hps/nobackup/juan/pride/reanalysis/quantms-ypriverol/quantms/bin/diann_convert.py:474: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value 'variable_modifications:Acetyl (Any N-term),Oxidation (M)' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
    out_mztab_MTD.loc[1, "software[1]-setting[12]"] = "variable_modifications:" + VariableModifications
  const OpenMS::ResidueModification* OpenMS::ModificationsDB::searchModificationsFast(const OpenMS::String&, bool&, const OpenMS::String&, OpenMS::ResidueModification::TermSpecificity) constModification not found: Acetyl (Any N-term)
  Warning: OPENMS_DATA_PATH environment variable not found and no share directory was installed. Some functionality might not work as expected.
  Traceback (most recent call last):
    File "/hps/nobackup/juan/pride/reanalysis/quantms-ypriverol/quantms/bin/diann_convert.py", line 1333, in <module>
      cli()
    File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1157, in __call__
      return self.main(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1078, in main
      rv = self.invoke(ctx)
           ^^^^^^^^^^^^^^^^
    File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1688, in invoke
      return _process_result(sub_ctx.command.invoke(sub_ctx))
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1434, in invoke
      return ctx.invoke(self.callback, **ctx.params)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/usr/local/lib/python3.11/site-packages/click/core.py", line 783, in invoke
      return __callback(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/usr/local/lib/python3.11/site-packages/click/decorators.py", line 33, in new_func
      return f(get_current_context(), *args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/hps/nobackup/juan/pride/reanalysis/quantms-ypriverol/quantms/bin/diann_convert.py", line 144, in convert
      diann_directory.convert_to_mztab(
    File "/hps/nobackup/juan/pride/reanalysis/quantms-ypriverol/quantms/bin/diann_convert.py", line 304, in convert_to_mztab
      (MTD, database) = mztab_MTD(index_ref, dia_params, str(self.fasta), charge, missed_cleavages)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/hps/nobackup/juan/pride/reanalysis/quantms-ypriverol/quantms/bin/diann_convert.py", line 476, in mztab_MTD
      (fixed_mods, variable_mods, fix_flag, var_flag) = MTD_mod_info(FixedModifications, VariableModifications)
                                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/hps/nobackup/juan/pride/reanalysis/quantms-ypriverol/quantms/bin/diann_convert.py", line 412, in MTD_mod_info
      mod_obj = mods_db.getModification(mod)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "pyopenms/_pyopenms_1.pyx", line 8193, in pyopenms._pyopenms_1.ModificationsDB.getModification
    File "pyopenms/_pyopenms_1.pyx", line 8140, in pyopenms._pyopenms_1.ModificationsDB._getModification_1
  RuntimeError: the value 'Acetyl (Any N-term)' was used but is not valid; Retrieving the modification failed. It is not available for the residue '' and term specificity 'none'. 

Work dir:
  /hps/nobackup/juan/pride/reanalysis/single-cell/PXD024043/work/5b/a02ba944e1bd20bb2fffde1e18c787

Tip: when you have fixed the problem you can continue the execution adding the option `-resume` to the run command line

 -- Check '.nextflow.log' file for details
```

**Comment by daichengxin** [comment]
It's due to the SDRF incorrect annotation. `TA=Any N-term` -> `PP=Any N-term`

**Comment by ypriverol** [comment]
Another error here: 

```
  /hps/nobackup/juan/pride/reanalysis/quantms-ypriverol/quantms/bin/diann_convert.py:812: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value 'null' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
    out_mztab_PEH.fillna("null", inplace=True)
  2023-10-30 08:59:17,390 [mztab_PSH] - Constructing PSH sub-table
  2023-10-30 08:59:20,376 [mztab_PSH] - Finding Modifications ...
  Warning: OPENMS_DATA_PATH environment variable not found and no share directory was installed. Some functionality might not work as expected.
  Traceback (most recent call last):
    File "/hps/nobackup/juan/pride/reanalysis/quantms-ypriverol/quantms/bin/diann_convert.py", line 1333, in <module>
      cli()
    File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1157, in __call__
      return self.main(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1078, in main
      rv = self.invoke(ctx)
           ^^^^^^^^^^^^^^^^
    File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1688, in invoke
      return _process_result(sub_ctx.command.invoke(sub_ctx))
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1434, in invoke
      return ctx.invoke(self.callback, **ctx.params)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/usr/local/lib/python3.11/site-packages/click/core.py", line 783, in invoke
      return __callback(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/usr/local/lib/python3.11/site-packages/click/decorators.py", line 33, in new_func
      return f(get_current_context(), *args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/hps/nobackup/juan/pride/reanalysis/quantms-ypriverol/quantms/bin/diann_convert.py", line 144, in convert
      diann_directory.convert_to_mztab(
    File "/hps/nobackup/juan/pride/reanalysis/quantms-ypriverol/quantms/bin/diann_convert.py", line 320, in convert_to_mztab
      PSH = mztab_PSH(report, str(self.base_path), database)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/hps/nobackup/juan/pride/reanalysis/quantms-ypriverol/quantms/bin/diann_convert.py", line 927, in mztab_PSH
      out_mztab_PSH.loc[:, "spectra_ref"] = out_mztab_PSH.apply(
                                            ^^^^^^^^^^^^^^^^^^^^
    File "/usr/local/lib/python3.11/site-packages/pandas/core/frame.py", line 10037, in apply
      return op.apply().__finalize__(self, method="apply")
             ^^^^^^^^^^
    File "/usr/local/lib/python3.11/site-packages/pandas/core/apply.py", line 837, in apply
      return self.apply_standard()
             ^^^^^^^^^^^^^^^^^^^^^
    File "/usr/local/lib/python3.11/site-packages/pandas/core/apply.py", line 963, in apply_standard
      results, res_index = self.apply_series_generator()
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/usr/local/lib/python3.11/site-packages/pandas/core/apply.py", line 979, in apply_series_generator
      results[i] = self.func(v, *self.args, **self.kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/hps/nobackup/juan/pride/reanalysis/quantms-ypriverol/quantms/bin/diann_convert.py", line 928, in <lambda>
      lambda x: "ms_run[{}]:".format(x["ms_run"]) + x["opt_global_spectrum_reference"], axis=1, result_type="expand"
                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  TypeError: can only concatenate str (not "int") to str

Command wrapper:
  /hps/nobackup/juan/pride/reanalysis/quantms-ypriverol/quantms/bin/diann_convert.py:812: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value 'null' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
    out_mztab_PEH.fillna("null", inplace=True)
  2023-10-30 08:59:17,390 [mztab_PSH] - Constructing PSH sub-table
  2023-10-30 08:59:20,376 [mztab_PSH] - Finding Modifications ...
  Warning: OPENMS_DATA_PATH environment variable not found and no share directory was installed. Some functionality might not work as expected.
  Traceback (most recent call last):
    File "/hps/nobackup/juan/pride/reanalysis/quantms-ypriverol/quantms/bin/diann_convert.py", line 1333, in <module>
      cli()
    File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1157, in __call__
      return self.main(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1078, in main
      rv = self.invoke(ctx)
           ^^^^^^^^^^^^^^^^
    File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1688, in invoke
      return _process_result(sub_ctx.command.invoke(sub_ctx))
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1434, in invoke
      return ctx.invoke(self.callback, **ctx.params)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/usr/local/lib/python3.11/site-packages/click/core.py", line 783, in invoke
      return __callback(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/usr/local/lib/python3.11/site-packages/click/decorators.py", line 33, in new_func
      return f(get_current_context(), *args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/hps/nobackup/juan/pride/reanalysis/quantms-ypriverol/quantms/bin/diann_convert.py", line 144, in convert
      diann_directory.convert_to_mztab(
    File "/hps/nobackup/juan/pride/reanalysis/quantms-ypriverol/quantms/bin/diann_convert.py", line 320, in convert_to_mztab
      PSH = mztab_PSH(report, str(self.base_path), database)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/hps/nobackup/juan/pride/reanalysis/quantms-ypriverol/quantms/bin/diann_convert.py", line 927, in mztab_PSH
      out_mztab_PSH.loc[:, "spectra_ref"] = out_mztab_PSH.apply(
                                            ^^^^^^^^^^^^^^^^^^^^
    File "/usr/local/lib/python3.11/site-packages/pandas/core/frame.py", line 10037, in apply
      return op.apply().__finalize__(self, method="apply")
             ^^^^^^^^^^
    File "/usr/local/lib/python3.11/site-packages/pandas/core/apply.py", line 837, in apply
      return self.apply_standard()
             ^^^^^^^^^^^^^^^^^^^^^
    File "/usr/local/lib/python3.11/site-packages/pandas/core/apply.py", line 963, in apply_standard
      results, res_index = self.apply_series_generator()
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/usr/local/lib/python3.11/site-packages/pandas/core/apply.py", line 979, in apply_series_generator
      results[i] = self.func(v, *self.args, **self.kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/hps/nobackup/juan/pride/reanalysis/quantms-ypriverol/quantms/bin/diann_convert.py", line 928, in <lambda>
      lambda x: "ms_run[{}]:".format(x["ms_run"]) + x["opt_global_spectrum_reference"], axis=1, result_type="expand"
                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  TypeError: can only concatenate str (not "int") to str

Work dir:
  /hps/nobackup/juan/pride/reanalysis/single-cell/PXD024043/work/1e/091ab7a8c7bceb781c5d02277e3f86

Tip: view the complete command output by changing to the process work dir and entering the command `cat .command.out`

 -- Check '.nextflow.log' file for details

```

**Comment by ypriverol** [comment]
Bug solved in PR https://github.com/nf-core/quantms/pull/125.
