### ISSUE TITLE
Big datasets more than 200 GB mztab size are not supported. 

### ISSUE THREAD

**Issue by ypriverol** [bigbio/quantms#342]
### Description of the bug

```
nf-core/quantms execution completed unsuccessfully!

The exit status of the task that caused the workflow execution to fail was: 1.

The full error message was:

Error executing process > 'NFCORE_QUANTMS:QUANTMS:SUMMARYPIPELINE (1)'

Caused by:
  Process `NFCORE_QUANTMS:QUANTMS:SUMMARYPIPELINE (1)` terminated with an error exit status (1)

Command executed:

  set -x
  set -e
  
  # leaving here to ease debugging
  ls -lcth *
  
  echo ">>>>>>>>> Experimental Design <<<<<<<<<"
  cat results/*openms_design.tsv
  
  echo ">>>>>>>>> Running Multiqc <<<<<<<<<"
  multiqc \
      -f \
      --config ./results/multiqc_config.yml \
       \
       \
       \
      --ignored_idxml \
      --quantification_method feature_intensity \
      ./results \
      -o .
  
  cat <<-END_VERSIONS > versions.yml
  "NFCORE_QUANTMS:QUANTMS:SUMMARYPIPELINE":
      pmultiqc: $(multiqc --pmultiqc_version | sed -e "s/pmultiqc, version //g")
  END_VERSIONS

Command exit status:
  1

Command output:
  413	JM1	413	42
  414	KASUMI-2	414	42
  415	KYM-1	415	42
  416	KYSE-410	416	42
  417	CL-34	417	42
  418	NCI-H446	418	42
  419	SK-N-AS	419	42
  420	mixed	420	42
  421	DAN-G	421	43
  422	KNS-42	422	43
  423	HEC-108	423	43
  424	JeKo-1	424	43
  425	JURKAT	425	43
  426	MSTO-211H	426	43
  427	OCUM-1	427	43
  428	CCK-81	428	43
  429	SNU-449	429	43
  430	mixed	430	43
  431	8505C	431	44
  432	HCC-1833	432	44
  433	Panc 04.03	433	44
  434	J82	434	44
  435	JHH-4	435	44
  436	OVSAHO	436	44
  437	RL	437	44
  438	SNU-C5	438	44
  439	SU-DHL-6	439	44
  440	mixed	440	44
  441	MFE-319	441	45
  442	HD-MY-Z	442	45
  443	HDQ-P1	443	45
  444	JHH-6	444	45
  445	L-428	445	45
  446	LMSU	446	45
  447	HUP-T4	447	45
  448	SW 1783	448	45
  449	UM-UC-3	449	45
  450	mixed	450	45
  451	SK-LU-1	451	46
  452	Ishikawa (Heraklio) 02 ER-	452	46
  453	SNG-M	453	46
  454	GAMG	454	46
  455	NCI-H929	455	46
  456	Panc 02.03	456	46
  457	RCH-ACV	457	46
  458	SNU-423	458	46
  459	SNU-1079	459	46
  460	mixed	460	46
  >>>>>>>>> Running Multiqc <<<<<<<<<
  Warning: OPENMS_DATA_PATH environment variable not found and no share directory was installed. Some functionality might not work as expected.

Command error:
  ================================================================================
  Traceback (most recent call last):
    File "/usr/local/lib/python3.11/site-packages/multiqc/multiqc.py", line 689, in run
      output = mod()
               ^^^^^
    File "/usr/local/lib/python3.11/site-packages/pmultiqc/modules/quantms/quantms.py", line 189, in __init__
      self.CalHeatMapScore()
    File "/usr/local/lib/python3.11/site-packages/pmultiqc/modules/quantms/quantms.py", line 1006, in CalHeatMapScore
      mztab_data = mztab.MzTab(self.out_mzTab_path)
                               ^^^^^^^^^^^^^^^^^^^
  AttributeError: 'QuantMSModule' object has no attribute 'out_mzTab_path'
  ================================================================================
  DEBUG:multiqc.modules.custom_content.custom_content:No samples found: custom content (total_ion_chromatograms)
  DEBUG:multiqc.modules.custom_content.custom_content:No samples found: custom content (base_peak_chromatograms)
  DEBUG:multiqc.modules.custom_content.custom_content:No samples found: custom content (number_of_peaks)
  DEBUG:multiqc.modules.custom_content.custom_content:No samples found: custom content (general_stats)
  |    custom_content | nf-core-quantms-methods-description: Found 1 sample (html)
  INFO:multiqc.modules.custom_content.custom_content:nf-core-quantms-methods-description: Found 1 sample (html)
  |    custom_content | software_versions: Found 1 sample (html)
  INFO:multiqc.modules.custom_content.custom_content:software_versions: Found 1 sample (html)
  |    custom_content | nf-core-quantms-summary: Found 1 sample (html)
  INFO:multiqc.modules.custom_content.custom_content:nf-core-quantms-summary: Found 1 sample (html)
  DEBUG:multiqc.utils.software_versions:Reading software versions from config.software_versions
  DEBUG:multiqc:Reordering sections: anchor 'pmultiqc' not found.
  DEBUG:multiqc:Reordering sections: anchor 'pmultiqc' not found for module 'nf-core/quantms Methods Description'.
  DEBUG:multiqc:Reordering sections: anchor 'nf-core-quantms-methods-description' not found for module 'nf-core/quantms Methods Description'.
  DEBUG:multiqc:Reordering sections: anchor 'software_versions' not found for module 'nf-core/quantms Methods Description'.
  DEBUG:multiqc:Reordering sections: anchor 'nf-core-quantms-summary' not found for module 'nf-core/quantms Methods Description'.
  DEBUG:multiqc:Reordering sections: anchor 'pmultiqc' not found for module 'nf-core/quantms Software Versions'.
  DEBUG:multiqc:Reordering sections: anchor 'nf-core-quantms-methods-description' not found for module 'nf-core/quantms Software Versions'.
  DEBUG:multiqc:Reordering sections: anchor 'software_versions' not found for module 'nf-core/quantms Software Versions'.
  DEBUG:multiqc:Reordering sections: anchor 'nf-core-quantms-summary' not found for module 'nf-core/quantms Software Versions'.
  DEBUG:multiqc:Reordering sections: anchor 'pmultiqc' not found for module 'nf-core/quantms Workflow Summary'.
  DEBUG:multiqc:Reordering sections: anchor 'nf-core-quantms-methods-description' not found for module 'nf-core/quantms Workflow Summary'.
  DEBUG:multiqc:Reordering sections: anchor 'software_versions' not found for module 'nf-core/quantms Workflow Summary'.
  DEBUG:multiqc:Reordering sections: anchor 'nf-core-quantms-summary' not found for module 'nf-core/quantms Workflow Summary'.
  DEBUG:multiqc:Compressing plot data
  |           multiqc | Report      : multiqc_report.html
  INFO:multiqc:Report      : multiqc_report.html
  |           multiqc | Data        : multiqc_data
  INFO:multiqc:Data        : multiqc_data
  DEBUG:multiqc:Moving data file from '/tmp/tmpj4s1blix/multiqc_data' to './multiqc_data'
  DEBUG:multiqc:Full report path: multiqc_report.html
  |           multiqc | Plots       : multiqc_plots
  INFO:multiqc:Plots       : multiqc_plots
  DEBUG:multiqc:Moving plots directory from '/tmp/tmpj4s1blix/multiqc_plots' to './multiqc_plots'
  |           multiqc | Flat-image plots used. Disable with '--interactive'. See 
  docs.
  |           multiqc | MultiQC complete
  INFO:multiqc:MultiQC complete

Work dir:
  /hps/nobackup/juan/pride/reanalysis/absolute-expression/cell-lines/MSV000085836/work/eb/7791f6ff8eecc1b55b0fd398dfe07a

Tip: you can replicate the issue by changing to the process work dir and entering the command `bash .command.run`
```

**Comment by ypriverol** [comment]
We are moving to quantms.io in the next release 1.5.0.
