### ISSUE TITLE
Unknown AA in peptide sequence compute MonoIsotopic Mass 

### ISSUE THREAD

**Issue by ypriverol** [bigbio/quantms#368]
### Description of the bug

When running the DIA workflow, the dia_convert give the following error if Uniprot Trembl is used: 

```
Caused by:
  Process `NFCORE_QUANTMS:QUANTMS:DIA:DIANNCONVERT (final_updated_QPLAP_test_metadata.sdrf)` terminated with an error exit status (1)

Command executed:

  diann_convert.py convert \
      --folder ./ \
      --exp_design final_updated_QPLAP_test_metadata.sdrf_openms_design.tsv \
      --diann_version ./version/versions.yml \
      --dia_params "0.5;Da;20.0;ppm;Trypsin;Carbamidomethyl (C);Acetyl (Protein N-term),Oxidation (M)" \
      --charge 4 \
      --missed_cleavages 1 \
      --qvalue_threshold 0.01 \
      2>&1 | tee convert_report.log

  cat <<-END_VERSIONS > versions.yml
  "NFCORE_QUANTMS:QUANTMS:DIA:DIANNCONVERT":
      pyopenms: $(pip show pyopenms | grep "Version" | awk -F ': ' '{print $2}')
  END_VERSIONS

Command exit status:
  1

Command output:
  2024-04-10 00:49:19,684 [convert] - Revision 0.1.1
  2024-04-10 00:49:19,684 [convert] - Reading input files...
  2024-04-10 00:49:23,275 [main_report_df] - Filtering report based on qvalue threshold: 0.01, 330767 rows
  2024-04-10 00:49:23,303 [main_report_df] - Report filtered, 330767 rows remaining
  2024-04-10 00:49:23,303 [main_report_df] - Calculating Precursor.Mz
  Warning: OPENMS_DATA_PATH environment variable not found and no share directory was installed. Some functionality might not work as expected.
  Traceback (most recent call last):
    File "/home-link/zxoqe31/.nextflow/assets/nf-core/quantms/bin/diann_convert.py", line 1331, in <module>
      cli()
    File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1157, in __call__
      return self.main(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1078, in main
      rv = self.invoke(ctx)
           ^^^^^^^^^^^^^^^^
 File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1688, in invoke
      return _process_result(sub_ctx.command.invoke(sub_ctx))
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1434, in invoke
      return ctx.invoke(self.callback, **ctx.params)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/usr/local/lib/python3.11/site-packages/click/core.py", line 783, in invoke
      return __callback(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/usr/local/lib/python3.11/site-packages/click/decorators.py", line 33, in new_func
      return f(get_current_context(), *args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/home-link/zxoqe31/.nextflow/assets/nf-core/quantms/bin/diann_convert.py", line 71, in convert
      report = diann_directory.main_report_df(qvalue_threshold=qvalue_threshold)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/home-link/zxoqe31/.nextflow/assets/nf-core/quantms/bin/diann_convert.py", line 352, in main_report_df
      uniq_masses = {k: AASequence.fromString(k).getMonoWeight() for k in report["Modified.Sequence"].unique()}
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/home-link/zxoqe31/.nextflow/assets/nf-core/quantms/bin/diann_convert.py", line 352, in <dictcomp>
      uniq_masses = {k: AASequence.fromString(k).getMonoWeight() for k in report["Modified.Sequence"].unique()}
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "pyopenms/_pyopenms_6.pyx", line 818, in pyopenms._pyopenms_6.AASequence.getMonoWeight
    File "pyopenms/_pyopenms_6.pyx", line 787, in pyopenms._pyopenms_6.AASequence._getMonoWeight_0
  RuntimeError: the value 'AVQVHQDTLRTMYFAXR' was used but is not valid; Cannot get weight of sequence with unknown AA 'X' with unknown mass.
```

The best way to solve that would be to see if pyopenms supports unknown aminoacids @timosachsenberg @jpfeuffer. If is not possible, then we need to find a way to handle them in quantms to mzTab.

**Comment by timosachsenberg** [comment]
OpenMS support unknown amino acids e.g. 'X' but calculating the precursor m/z is not allowed
We support unknown amino acids with masses X[123.4] but you need to know the mass.
What does DIA-NN output?

**Comment by ypriverol** [comment]
DIA-NN used `Selenomethionine`

**Comment by jpfeuffer** [comment]
No, in this case, replace with the actual mass of a Selenomethionine residue

**Comment by jpfeuffer** [comment]
Or add a new Residue to the ResidueDB and set the onelettercode to something meaningful

**Comment by timosachsenberg** [comment]
I think all single letter codes are taken…
________________________________
Von: Julianus Pfeuffer ***@***.***>
Gesendet: Dienstag, 16. April 2024 17:12:59
An: bigbio/quantms
Cc: Timo Sachsenberg; Mention
Betreff: Re: [bigbio/quantms] Unknown AA in peptide sequence compute MonoIsotopic Mass (Issue #368)


Or add a new Residue to the ResidueDB and set the onelettercode to something meaningful

**Comment by ypriverol** [comment]
> No, in this case, replace with the actual mass of a Selenomethionine residue

What will be this solution? @timosachsenberg @jpfeuffer ?

**Comment by jpfeuffer** [comment]
196.995499

Probably -H2O

**Comment by ypriverol** [comment]
@jpfeuffer but the way to reply will be: 

`k.replace('X', '[196.995499]')`

My point is the notations.

**Comment by ypriverol** [comment]
@timosachsenberg `-18`?

**Comment by timosachsenberg** [comment]
yes without the water.

**Comment by timosachsenberg** [comment]
AASequence aa2 = AASequence::fromString("PEPTC(Carbamidomethyl)IDE");
  AASequence aa6 = AASequence::fromString("PEPTX[160.030654]IDE");

have same mass.
Cysteine **resdiue** is 103.0, Carbamidomethyl is +57.3 so the value in the bracket is the residue mass.
For Selenomethionine it is thus 178.98494

**Comment by timosachsenberg** [comment]
@cbielow pinging here to check if this is properly documented

**Comment by ypriverol** [comment]
@timosachsenberg @jpfeuffer : 

I will use the following: 
```                                 dia-nn mass - dia-nn HO mass   -  diann proton mass  
X -> X[178.98493453312]   # 196.995499 - 17.003288 - 1.00727646688
U -> U[132.94306553312]   # 150.95363   - 17.003288 - 1.00727646688
O -> O[237.14773053312]    # 255.158295 - 17.003288 - 1.00727646688        
```

**Comment by timosachsenberg** [comment]
What is U and O?
would U->X be better (you wrote U->U) ? or how does DIA-NN encode it in the sequence? 
```
U -> X[132.94306553312]   # 150.95363   - 17.003288 - 1.00727646688
O -> X[237.14773053312]    # 255.158295 - 17.003288 - 1.00727646688        
```

**Comment by ypriverol** [comment]
This is the message from Vadim: 
```
AA['U'] = 150.95363;
AA['X'] = 196.995499;
AA['O'] = 255.158295;
const double proton = 1.00727646688;
const double OH = 17.003288;
```

**Comment by timosachsenberg** [comment]
I guess both works in OpenMS but I think using X for everything "unknown" or non standard residue could be more convenient (and better tested) ;) .

**Comment by ypriverol** [comment]
> I guess both works in OpenMS but I think using X for everything "unknown" or non standard residue could be more convenient (and better tested) ;) .

PR now ready: https://github.com/bigbio/quantms/pull/369
