### ISSUE TITLE
mztab export fails for particular dataset from user. 

### ISSUE THREAD

**Issue by ypriverol** [bigbio/quantms#427]
### Description of the bug

Reported here: https://nfcore.slack.com/archives/C02Q3FL29PD/p1728424167422049

```
Command error:
  2024-10-08 21:43:49,054 [mztab_prh] - Calculating protein coverage (bottleneck)...
  2024-10-08 21:44:04,074 [mztab_prh] - Getting ambiguity members...
  2024-10-08 21:44:04,087 [mztab_prh] - Matching PRH to best search engine score...
  2024-10-08 21:44:04,246 [mztab_prh] - Matching PRH to modifications...
  2024-10-08 21:44:04,263 [mztab_prh] - Matching PRH to protein quantification...
  2024-10-08 21:44:04,323 [mztab_peh] - Constructing PEH sub-table...
  2024-10-08 21:44:04,323 [mztab_peh] - report.shape: (23503, 23),  pr.shape: (7377, 15), len(precursor_list): 8833, index_ref.shape: (5, 6)
  2024-10-08 21:44:04,326 [mztab_peh] - Finding modifications...
  2024-10-08 21:44:04,376 [mztab_peh] - Extracting sequence...
  2024-10-08 21:44:04,425 [mztab_peh] - Checking accession uniqueness...
  2024-10-08 21:44:04,464 [mztab_peh] - Matching precursor IDs...
  2024-10-08 21:44:04,469 [mztab_peh] - Getting scores per run
  2024-10-08 21:44:04,493 [mztab_peh] - Getting peptide abundances per study variable
  2024-10-08 21:44:04,524 [mztab_peh] - Getting peptide properties...
  2024-10-08 21:44:04,536 [mztab_peh] - Re-ordering columns...
  2024-10-08 21:44:04,569 [mztab_psh] - Constructing PSH sub-table
  /usr/local/lib/python3.10/site-packages/quantmsutils/diann/diann2mztab.py:1089: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
    for n, group in report.groupby(["Run"]):
  Traceback (most recent call last):
    File "/usr/local/bin/quantmsutilsc", line 10, in <module>
      sys.exit(main())
    File "/usr/local/lib/python3.10/site-packages/quantmsutils/quantmsutilsc.py", line 38, in main
      cli()
    File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
      return self.main(*args, **kwargs)
    File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1078, in main
      rv = self.invoke(ctx)
    File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1688, in invoke
      return _process_result(sub_ctx.command.invoke(sub_ctx))
    File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
      return ctx.invoke(self.callback, **ctx.params)
    File "/usr/local/lib/python3.10/site-packages/click/core.py", line 783, in invoke
      return __callback(*args, **kwargs)
    File "/usr/local/lib/python3.10/site-packages/click/decorators.py", line 33, in new_func
      return f(get_current_context(), *args, **kwargs)
    File "/usr/local/lib/python3.10/site-packages/quantmsutils/diann/diann2mztab.py", line 181, in diann2mztab
      diann_directory.convert_to_mztab(
    File "/usr/local/lib/python3.10/site-packages/quantmsutils/diann/diann2mztab.py", line 431, in convert_to_mztab
      psh = mztab_psh(report, str(self.base_path), database)
    File "/usr/local/lib/python3.10/site-packages/quantmsutils/diann/diann2mztab.py", line 1116, in mztab_psh
      pd.merge_asof(group, target, on="RT.Start", direction="nearest"),
    File "/usr/local/lib/python3.10/site-packages/pandas/core/reshape/merge.py", line 600, in merge_asof
      return op.get_result()
    File "/usr/local/lib/python3.10/site-packages/pandas/core/reshape/merge.py", line 1742, in get_result
      join_index, left_indexer, right_indexer = self._get_join_info()
    File "/usr/local/lib/python3.10/site-packages/pandas/core/reshape/merge.py", line 1026, in _get_join_info
      (left_indexer, right_indexer) = self._get_join_indexers()
    File "/usr/local/lib/python3.10/site-packages/pandas/core/reshape/merge.py", line 2042, in _get_join_indexers
      raise ValueError(f"Merge keys contain null values on {side} side")
  ValueError: Merge keys contain null values on right side
```

**Comment by ypriverol** [comment]
Solved
