### ISSUE TITLE
quantms utils Acetyl Unimod:1 error 

### ISSUE THREAD

**Issue by ypriverol** [bigbio/quantms#466]
### Description of the bug

```
Workflow execution completed unsuccessfully
The exit status of the task that caused the workflow execution to fail was: 1

Error executing process > 'BIGBIO_QUANTMS:QUANTMS:DIA:DIANNCONVERT (PXD048325-Hela.sdrf)'

Caused by:
  Process `BIGBIO_QUANTMS:QUANTMS:DIA:DIANNCONVERT (PXD048325-Hela.sdrf)` terminated with an error exit status (1)


Command executed:

  quantmsutilsc diann2mztab \
      --folder ./ \
      --exp_design PXD048325-Hela.sdrf_openms_design.tsv \
      --diann_version ./version/versions.yml \
      --dia_params "40.0;ppm;40.0;ppm;Trypsin;Carbamidomethyl (C);Acetyl (Any N-term),Oxidation (M)" \
      --charge 4 \
      --missed_cleavages 1 \
      --qvalue_threshold 0.01 \
       \
      2>&1 | tee convert_report.log
  
  cat <<-END_VERSIONS > versions.yml
  "BIGBIO_QUANTMS:QUANTMS:DIA:DIANNCONVERT":
      quantms-utils: $(pip show quantms-utils | grep "Version" | awk -F ': ' '{print $2}')
  END_VERSIONS

Command exit status:
  1

Command output:
  2024-12-26 00:51:36,655 [compute_mass_modified_peptide] - ADLATAPPHVTVVR:1445.7990694133002
  2024-12-26 00:51:36,655 [compute_mass_modified_peptide] - ADLDATLYEQVLLEK:1719.8930919875
  2024-12-26 00:51:36,655 [compute_mass_modified_peptide] - ADLDLSGPNVDVDVPDVNLEGPDAK:2563.228972550601
  2024-12-26 00:51:36,655 [compute_mass_modified_peptide] - ADLDLTK:774.4123388501998
  2024-12-26 00:51:36,655 [compute_mass_modified_peptide] - ADLDLTKR:930.5134502329998
  2024-12-26 00:51:36,655 [compute_mass_modified_peptide] - ADLDLVTMDYAAQK:1552.7443181752
  2024-12-26 00:51:36,655 [compute_mass_modified_peptide] - ADLDVSGPK:900.4552670415999
  2024-12-26 00:51:36,655 [compute_mass_modified_peptide] - ADLDVSGPKVDLDTPDLDLHGPEGK:2602.2762567101013
  2024-12-26 00:51:36,655 [compute_mass_modified_peptide] - ADLDVSGPKVDLDVPDVNLEGPDAK:2577.281007742001
  2024-12-26 00:51:36,655 [compute_mass_modified_peptide] - ADLDVSGPKVDLDVPDVNLEGPEGK:2577.281007742001
  2024-12-26 00:51:36,655 [compute_mass_modified_peptide] - ADLDVSGPKVDLEGPDVNLEGPEGK:2549.249707614401
  2024-12-26 00:51:36,655 [compute_mass_modified_peptide] - ADLDVSGPKVDVDLPDVNLEGPDAK:2577.281007742001
  2024-12-26 00:51:36,655 [compute_mass_modified_peptide] - ADLDVSGPKVDVDVPDVNLEGPDAK:2563.265357678201
  2024-12-26 00:51:36,655 [compute_mass_modified_peptide] - ADLDVSGPKVDVEC(UniMod:4)PDVNLEGPEGK:2638.243242440101
  2024-12-26 00:51:36,655 [compute_mass_modified_peptide] - ADLDVSGPKVDVEVPDVSLEGPEGK:2550.270108710101
  Traceback (most recent call last):
    File "/usr/local/bin/quantmsutilsc", line 10, in <module>
      sys.exit(main())
               ^^^^^^
    File "/usr/local/lib/python3.12/site-packages/quantmsutils/quantmsutilsc.py", line 36, in main
      cli()
    File "/usr/local/lib/python3.12/site-packages/click/core.py", line 1157, in __call__
      return self.main(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/usr/local/lib/python3.12/site-packages/click/core.py", line 1078, in main
      rv = self.invoke(ctx)
           ^^^^^^^^^^^^^^^^
    File "/usr/local/lib/python3.12/site-packages/click/core.py", line 1688, in invoke
      return _process_result(sub_ctx.command.invoke(sub_ctx))
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/usr/local/lib/python3.12/site-packages/click/core.py", line 1434, in invoke
      return ctx.invoke(self.callback, **ctx.params)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/usr/local/lib/python3.12/site-packages/click/core.py", line 783, in invoke
      return __callback(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/usr/local/lib/python3.12/site-packages/click/decorators.py", line 33, in new_func
      return f(get_current_context(), *args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/usr/local/lib/python3.12/site-packages/quantmsutils/diann/diann2mztab.py", line 84, in diann2mztab
      report = diann_directory.main_report_df(qvalue_threshold=qvalue_threshold)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/usr/local/lib/python3.12/site-packages/quantmsutils/diann/diann2mztab.py", line 481, in main_report_df
      k: compute_mass_modified_peptide(k) for k in report["Modified.Sequence"].unique()
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/usr/local/lib/python3.12/site-packages/quantmsutils/diann/diann2mztab.py", line 299, in compute_mass_modified_peptide
      mass = AASequence.fromString(new_peptide_seq).getMonoWeight()
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "pyopenms/_pyopenms_5.pyx", line 31, in pyopenms._pyopenms_5.__static_AASequence_fromString
  RuntimeError: the value 'UniMod:1' was used but is not valid; Cannot convert string to peptide modification. No modification matches in our database.

Command wrapper:
  2024-12-26 00:51:36,655 [compute_mass_modified_peptide] - ADLATAPPHVTVVR:1445.7990694133002
  2024-12-26 00:51:36,655 [compute_mass_modified_peptide] - ADLDATLYEQVLLEK:1719.8930919875
  2024-12-26 00:51:36,655 [compute_mass_modified_peptide] - ADLDLSGPNVDVDVPDVNLEGPDAK:2563.228972550601
  2024-12-26 00:51:36,655 [compute_mass_modified_peptide] - ADLDLTK:774.4123388501998
  2024-12-26 00:51:36,655 [compute_mass_modified_peptide] - ADLDLTKR:930.5134502329998
  2024-12-26 00:51:36,655 [compute_mass_modified_peptide] - ADLDLVTMDYAAQK:1552.7443181752
  2024-12-26 00:51:36,655 [compute_mass_modified_peptide] - ADLDVSGPK:900.4552670415999
  2024-12-26 00:51:36,655 [compute_mass_modified_peptide] - ADLDVSGPKVDLDTPDLDLHGPEGK:2602.2762567101013
  2024-12-26 00:51:36,655 [compute_mass_modified_peptide] - ADLDVSGPKVDLDVPDVNLEGPDAK:2577.281007742001
  2024-12-26 00:51:36,655 [compute_mass_modified_peptide] - ADLDVSGPKVDLDVPDVNLEGPEGK:2577.281007742001
  2024-12-26 00:51:36,655 [compute_mass_modified_peptide] - ADLDVSGPKVDLEGPDVNLEGPEGK:2549.249707614401
  2024-12-26 00:51:36,655 [compute_mass_modified_peptide] - ADLDVSGPKVDVDLPDVNLEGPDAK:2577.281007742001
  2024-12-26 00:51:36,655 [compute_mass_modified_peptide] - ADLDVSGPKVDVDVPDVNLEGPDAK:2563.265357678201
  2024-12-26 00:51:36,655 [compute_mass_modified_peptide] - ADLDVSGPKVDVEC(UniMod:4)PDVNLEGPEGK:2638.243242440101
  2024-12-26 00:51:36,655 [compute_mass_modified_peptide] - ADLDVSGPKVDVEVPDVSLEGPEGK:2550.270108710101
  Traceback (most recent call last):
    File "/usr/local/bin/quantmsutilsc", line 10, in <module>
      sys.exit(main())
               ^^^^^^
    File "/usr/local/lib/python3.12/site-packages/quantmsutils/quantmsutilsc.py", line 36, in main
      cli()
    File "/usr/local/lib/python3.12/site-packages/click/core.py", line 1157, in __call__
      return self.main(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/usr/local/lib/python3.12/site-packages/click/core.py", line 1078, in main
      rv = self.invoke(ctx)
           ^^^^^^^^^^^^^^^^
    File "/usr/local/lib/python3.12/site-packages/click/core.py", line 1688, in invoke
      return _process_result(sub_ctx.command.invoke(sub_ctx))
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/usr/local/lib/python3.12/site-packages/click/core.py", line 1434, in invoke
      return ctx.invoke(self.callback, **ctx.params)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/usr/local/lib/python3.12/site-packages/click/core.py", line 783, in invoke
      return __callback(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/usr/local/lib/python3.12/site-packages/click/decorators.py", line 33, in new_func
      return f(get_current_context(), *args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/usr/local/lib/python3.12/site-packages/quantmsutils/diann/diann2mztab.py", line 84, in diann2mztab
      report = diann_directory.main_report_df(qvalue_threshold=qvalue_threshold)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/usr/local/lib/python3.12/site-packages/quantmsutils/diann/diann2mztab.py", line 481, in main_report_df
      k: compute_mass_modified_peptide(k) for k in report["Modified.Sequence"].unique()
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/usr/local/lib/python3.12/site-packages/quantmsutils/diann/diann2mztab.py", line 299, in compute_mass_modified_peptide
      mass = AASequence.fromString(new_peptide_seq).getMonoWeight()
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "pyopenms/_pyopenms_5.pyx", line 31, in pyopenms._pyopenms_5.__static_AASequence_fromString
  RuntimeError: the value 'UniMod:1' was used but is not valid; Cannot convert string to peptide modification. No modification matches in our database.

Work dir:
  /hps/nobackup/juan/pride/reanalysis/absolute-expression/cell-lines/PXD048325/work/5f/cfc150c913dda165696db769016216

Container:
  /hps/nobackup/juan/pride/reanalysis/singularity/depot.galaxyproject.org-singularity-quantms-utils-0.0.18--pyh7e72e81_0.img

Tip: view the complete command output by changing to the process work dir and entering the command `cat .command.out`
```

**Comment by daichengxin** [comment]
Amino acid Acetyl (not in peptide N-term) is not supported in pyopenms modification database like these: APLLA(UniMod:1)VTR、ASGN(UniMod:1)YATVLSHNPETKK. There are 162 modiified peptides in this DIA-NN results like these. DIA-NN modification parameters passed is `--var-mod Acetyl,42.010565,Any N-term`

**Comment by ypriverol** [comment]
@vdemichev have you seen this problem before, when searching with the parameter `--var-mod Acetyl,42.010565,Any N-term`, we got a lot of peptides with Acetyl in the middle of the sequence (e.g. `ASGN(UniMod:1)YATVLSHNPETKK`)

**Comment by vdemichev** [comment]
> --var-mod Acetyl,42.010565,Any N-term

Hi both, that's incorrect syntax, should be `--var-mod Acetyl,42.010565,n`

Best,
Vadim

**Comment by ypriverol** [comment]
Solved, acetylation: `NT=Acetyl;MT=Variable;PP=Any N-term;AC=UNIMOD:1`
